name: Deploy React Docker

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        default: "production"
        type: string

jobs:
  deploy:
    name: Deploy React on EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -T -i ~/.ssh/id_rsa ${{ secrets.AWS_USERNAME }}@${{ secrets.AWS_EC2_PUBLIC_IP }} << 'EOF'
        cd FSD-react
        git stash
        git pull origin main

    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify your Node.js version

    - name: Install Dependencies
      run: |
        npm install

    - name: Start Application
        run: |
          npm start